#:schema https://rlbot.org/schemas/agent.json
[settings]
# The name that will be displayed in game
name = "ExampleBot2"
# Path to loadout config from runner
loadout_file = "loadout.toml"
# (OPTIONAL) - what you want the working directory set to
# This is relative to the location of this file
# instead of setting to an empty string,
# this value can be removed from the file
root_dir = ""
# The command RLBot will call to start your bot on Windows
# ex: "bot.exe" for compiled bots, or "python bot.py" if you don't want to freeze your python bot
run_command = "python ExampleBot2.py"
# The command RLBot will call to start your bot on linux
# If this isn't set, RLBot may attempt to run the Windows command under Wine
run_command_linux = "../venv/bin/python ExampleBot2.py"
# This must be a unqiue identifier for your bot
# recommended format is "developer/botname"
agent_id = "rlbot_community/python_example"
# This is the path to your bot's logo image,
# which will be displayed in the GUI
# The example bot does not have a logo
logo_file = ""

# These values are optional but useful metadata for helper programs
[details]
# Short description of the bot
description = """
 What a more complex bot looks like with GoslingUtils v5
"""
# Fun fact about the bot
fun_fact = "You're reading a fun fact!"
# Link to your repository
source_link = "https://github.com/RLBot/python-example"
# Name of the bot's creator/developer
developer = "You, Martico2432 and GooseFairy#6680"
# Programming language
language = "Python"
# ALL POSSIBLE TAGS: 1v1, teamplay, goalie, hoops, dropshot, snow-day, rumble, spike-rush, heatseeker, memebot
# NOTE: Only add the goalie tag if your bot only plays as a goalie; this directly contrasts with the teamplay tag!
# NOTE: Only add a tag for a special game mode if you bot properly supports it
tags = []